<?php

// config/profanity.php

return [
    /*
    |--------------------------------------------------------------------------
    | Daftar Kata-kata yang Disensor
    |--------------------------------------------------------------------------
    |
    | Tambahkan semua kata-kata tidak pantas di dalam array ini.
    | Sistem akan memeriksa setiap kata secara case-insensitive (tidak peduli huruf besar/kecil).
    |
    */
    'words' => [
        'bodoh',
        'gila',
        'jelek',
        'anjing',
        'babi',
        'monyet',
        'setan',
        'iblis',
        'jahanam',
        'bajingan',
        'brengsek',
        'bedebah',
        'kontol',
        'memek',
        'perek',
        'tai',
        'taik',
        'taek',
        'jancok',
        'cuk',
        'goblok',
        'tolol',
        'bego',
        'peler',
        'pler',
        'fuck',
        'shit',
        'bitch',
        'bastard',
        'asshole',
        'cunt',
        'damn',
        'wanker',
        'kuso',
        'くそ',
        'shine',
        '死ね',
        'bakayarou',
        '馬鹿野郎',
        'chikushō',
        'ちくしょう',
        'kono yarou',
        'この野郎',
        'uzai',
        'うざい',
        'ssibal',
        'shibal',
        '씨발',
        'gaesaekki',
        '개새끼',
        'michin nom',
        'michin nyeon',
        '미친놈',
        '미친년',
        'byeongshin',
        '병신',
        'kkeojyeo',
        '꺼져',
        'jiral',
        '지랄',
        'cào nǐ mā',
        '操你妈',
        'shǎ bī',
        '傻逼',
        'wángbādàn',
        '王八蛋',
        'cào',
        '肏',
        '滚',
        'mierda',
        'joder',
        'puta',
        'hijo de puta',
        'coño',
        'cabrón',
        'scheiße',
        'arschloch',
        'fick dich',
        'hurensohn',
        'wichser',
        'merde',
        'putain',
        'fils de put,e',
        'con',
        'connard',
        'va te faire foutre',
        'suka',
        'сука',
        'blyad',
        'блядь',
        'khuy',
        'хуй',
        'pizdets',
        'пиздец',
        'yob tvoyu mat',
        'ёб твою мать',
        'kuss ummak',
        'كس أمك',
        'yalan abuk',
        'يلعن أبوك',
        'hayawan',
        'حيوان',
        'kalb',
        'كلب',
        'khara',
        'خرا',
        'godverdomme',
        'kut',
        'klootzak',
        'lul',
        'tering',
        'kanker',
        'cazzo',
        'vaffanculo',
        'stronzo',
        'figlio di puttana',
        'foda-se',
        'filho da puta',
        'caralho',
        'porra',
        'siktir git',
        'orospu çocuğu',
        'pezevenk',
        'amcık',
        'yarrak',
        'địt mẹ',
        'đụ má',
        'cút',
        'chó cht',
        'putang ina mo',
        'gago',
        'gaga',
        'tarantado',
        'leche',

    ],
];
